# Generated by Django 5.1.7 on 2025-04-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='lase_name',
            new_name='last_name',
        ),
    ]
