# Generated by Django 5.1.7 on 2025-04-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_firstname_contact_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
