# Generated by Django 5.1.7 on 2025-04-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mobile',
            new_name='customer_need',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='0000000000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='car_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
